"""baseline: current securities schema

Revision ID: 1f83c47309ef
Revises: 
Create Date: 2026-08-02 01:01:17.866716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f83c47309ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_definitions',
    sa.Column('factor', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('factor')
    )
    op.create_table('factor_returns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('factor', sa.String(), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('ret', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor', 'ts', 'source', name='uq_factor_ts_source')
    )
    with op.batch_alter_table('factor_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factor_returns_factor'), ['factor'], unique=False)
        batch_op.create_index(batch_op.f('ix_factor_returns_ts'), ['ts'], unique=False)

    op.create_table('securities',
    sa.Column('instrument_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('security_name', sa.String(), nullable=True),
    sa.Column('security_type', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('cusip', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('composite_figi', sa.String(), nullable=True),
    sa.Column('primary_exch_code', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_ticker'), ['ticker'], unique=False)

    op.create_table('trading_calendar',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'session_date', name='uq_calendar_exch_date')
    )
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_calendar_exchange'), ['exchange'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_calendar_session_date'), ['session_date'], unique=False)

    op.create_table('betas',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('benchmark', sa.String(), nullable=False),
    sa.Column('lookback', sa.Integer(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('beta_raw', sa.Float(), nullable=False),
    sa.Column('var_ols', sa.Float(), nullable=False),
    sa.Column('n_obs', sa.Integer(), nullable=False),
    sa.Column('prior_var', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['securities.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ts', 'benchmark')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('SPLIT', 'SYMBOL_CHANGE', 'DELISTING', 'SPINOFF', name='corporateactiontype'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['securities.instrument_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'effective_date', 'action_type', 'source', name='uq_ca_sec_date_type_source')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_actions_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('dividends',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['securities.instrument_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ex_date', 'source', name='uq_div_sec_ex_source')
    )
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dividends_ex_date'), ['ex_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('factor_loadings',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('factor', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('loading', sa.Float(), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('n_obs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['securities.instrument_id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'ts', 'factor', 'model')
    )
    op.create_table('prices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['securities.instrument_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'ts', 'source', name='uq_price_sec_ts_source')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_ts'))
        batch_op.drop_index(batch_op.f('ix_prices_instrument_id'))

    op.drop_table('prices')
    op.drop_table('factor_loadings')
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividends_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_dividends_ex_date'))

    op.drop_table('dividends')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_corporate_actions_effective_date'))

    op.drop_table('corporate_actions')
    op.drop_table('betas')
    with op.batch_alter_table('trading_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_calendar_session_date'))
        batch_op.drop_index(batch_op.f('ix_trading_calendar_exchange'))

    op.drop_table('trading_calendar')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_ticker'))

    op.drop_table('securities')
    with op.batch_alter_table('factor_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factor_returns_ts'))
        batch_op.drop_index(batch_op.f('ix_factor_returns_factor'))

    op.drop_table('factor_returns')
    op.drop_table('factor_definitions')
    # ### end Alembic commands ###
    # MANUALLY ADDED (autogenerate doesn't emit these): op.drop_table() does not drop the
    # Postgres native ENUM TYPE a dropped table's column used -- without this, a downgrade
    # followed by a re-upgrade fails with "type ... already exists" (verified empirically
    # on the portfolio DB's baseline). No-op on SQLite. Dropped last, after the table that
    # referenced it is already gone.
    sa.Enum(name="corporateactiontype").drop(op.get_bind(), checkfirst=True)
