"""baseline: current macro schema

Revision ID: 9974f4c2254d
Revises: 
Create Date: 2026-08-02 01:01:24.805901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9974f4c2254d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_series',
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('series_class', sa.Enum('MARKET', 'ECON', name='seriesclass'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='frequency'), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('observation_type', sa.Enum('STOCK', 'FLOW', 'NA', name='observationtype'), nullable=False),
    sa.Column('value_type', sa.Enum('LEVEL', 'PRICE', 'INDEX', 'RATIO', 'RATE', 'RATE_OF_CHANGE', 'DIFFUSION', 'SPREAD', 'YIELD', 'COUNT', 'CURRENCY', name='valuetype'), nullable=False),
    sa.Column('stationarity', sa.Enum('STATIONARY', 'NONSTATIONARY', 'UNKNOWN', name='stationarity'), nullable=False),
    sa.Column('transform_op', sa.Enum('NONE', 'DIFF', 'LOG_DIFF', 'PCT_CHANGE', 'ANNUALIZE', 'ZSCORE', name='transformop'), nullable=False),
    sa.Column('transform_horizon', sa.Enum('NONE', 'POP', 'YOY', name='transformhorizon'), nullable=False),
    sa.Column('seasonal_adjustment', sa.Enum('SA', 'NSA', 'NA', name='seasonaladjustment'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('series_id')
    )
    with op.batch_alter_table('macro_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_series_series_class'), ['series_class'], unique=False)

    op.create_table('macro_observations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'obs_date', 'source', name='uq_macroobs_series_date_source')
    )
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_observations_obs_date'), ['obs_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_observations_series_id'), ['series_id'], unique=False)

    op.create_table('macro_release_calendar',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('scheduled_release_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'reference_date', name='uq_macrorel_series_ref')
    )
    with op.batch_alter_table('macro_release_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_release_calendar_series_id'), ['series_id'], unique=False)

    op.create_table('macro_vintages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('vintage_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.series_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'reference_date', 'vintage_date', 'source', name='uq_macrovint_series_ref_vint_source')
    )
    with op.batch_alter_table('macro_vintages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macro_vintages_reference_date'), ['reference_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_vintages_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_macro_vintages_vintage_date'), ['vintage_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('macro_vintages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_vintages_vintage_date'))
        batch_op.drop_index(batch_op.f('ix_macro_vintages_series_id'))
        batch_op.drop_index(batch_op.f('ix_macro_vintages_reference_date'))

    op.drop_table('macro_vintages')
    with op.batch_alter_table('macro_release_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_release_calendar_series_id'))

    op.drop_table('macro_release_calendar')
    with op.batch_alter_table('macro_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_observations_series_id'))
        batch_op.drop_index(batch_op.f('ix_macro_observations_obs_date'))

    op.drop_table('macro_observations')
    with op.batch_alter_table('macro_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macro_series_series_class'))

    op.drop_table('macro_series')
    # ### end Alembic commands ###
    # MANUALLY ADDED (autogenerate doesn't emit these): op.drop_table() does not drop the
    # Postgres native ENUM TYPEs macro_series' columns used -- without this, a downgrade
    # followed by a re-upgrade fails with "type ... already exists" (verified empirically
    # on the portfolio DB's baseline). No-op on SQLite. Dropped last, after the table that
    # referenced them is already gone.
    for enum_name in (
        "seasonaladjustment", "transformhorizon", "transformop", "stationarity",
        "valuetype", "observationtype", "frequency", "seriesclass",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
