"""Securities (market-data) database schema tests (in-memory SQLite).

Covers the universe projection anchor and the market-data facts that hang off it —
prices, dividends, and corporate actions (splits etc.). The split ratio is what lets raw
historical prices be adjusted, so it gets an explicit round-trip.
"""
from __future__ import annotations

from datetime import date

import pytest
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from neptune.securities.models import (
    CorporateAction,
    CorporateActionType,
    Dividend,
    Price,
    Security,
    TradingDay,
)


def _seed_security(session, instrument_id: int = 320193, ticker: str = "AAPL") -> Security:
    """Project one universe instrument into the local anchor table."""
    sec = Security(
        instrument_id=instrument_id,
        ticker=ticker,
        security_name="Apple Inc.",
        security_type="Common Stock",
        primary_exch_code="UW",
        currency="USD",
        source="cato_securities",
    )
    session.add(sec)
    session.commit()
    return sec


def test_security_projection_round_trips(securities_session):
    _seed_security(securities_session)
    [sec] = securities_session.scalars(select(Security)).all()
    # instrument_id is the universe surrogate — stored, not autogenerated.
    assert sec.instrument_id == 320193
    assert sec.ticker == "AAPL"
    assert sec.is_active is True


def test_prices_and_dividends_link_to_security(securities_session):
    _seed_security(securities_session)
    securities_session.add_all(
        [
            Price(
                instrument_id=320193, ts=date(2026, 5, 28), close=190.0,
                adj_close=190.0, volume=1_000_000, source="yfinance",
            ),
            Price(
                instrument_id=320193, ts=date(2026, 5, 29), close=192.0,
                adj_close=192.0, volume=1_100_000, source="yfinance",
            ),
            Dividend(
                instrument_id=320193, ex_date=date(2026, 5, 9),
                pay_date=date(2026, 5, 15), amount=0.25, source="yfinance",
            ),
        ]
    )
    securities_session.commit()

    sec = securities_session.get(Security, 320193)
    assert {p.ts for p in sec.prices} == {date(2026, 5, 28), date(2026, 5, 29)}
    assert [d.amount for d in sec.dividends] == [0.25]


def test_split_corporate_action_carries_ratio(securities_session):
    """A 4:1 forward split must persist its ratio so historical prices can be adjusted."""
    _seed_security(securities_session)
    securities_session.add(
        CorporateAction(
            instrument_id=320193,
            action_type=CorporateActionType.SPLIT,
            effective_date=date(2020, 8, 31),
            ratio=4.0,
            source="yfinance",
        )
    )
    securities_session.commit()

    [ca] = securities_session.scalars(
        select(CorporateAction).where(
            CorporateAction.action_type == CorporateActionType.SPLIT
        )
    ).all()
    assert ca.ratio == 4.0
    assert ca.effective_date == date(2020, 8, 31)


def test_symbol_change_uses_old_new_values(securities_session):
    _seed_security(securities_session, instrument_id=12345, ticker="META")
    securities_session.add(
        CorporateAction(
            instrument_id=12345,
            action_type=CorporateActionType.SYMBOL_CHANGE,
            effective_date=date(2022, 6, 9),
            old_value="FB",
            new_value="META",
            source="manual",
        )
    )
    securities_session.commit()
    [ca] = securities_session.scalars(select(CorporateAction)).all()
    assert (ca.old_value, ca.new_value) == ("FB", "META")


def test_prices_are_append_only_across_sources(securities_session):
    """Same (security, day) from two different sources coexist; the unique key includes
    source, so neither silently overwrites the other (invariant I-07)."""
    _seed_security(securities_session)
    securities_session.add_all(
        [
            Price(instrument_id=320193, ts=date(2026, 5, 29), close=192.0, source="yfinance"),
            Price(instrument_id=320193, ts=date(2026, 5, 29), close=192.1, source="bloomberg"),
        ]
    )
    securities_session.commit()
    rows = securities_session.scalars(
        select(Price).where(Price.ts == date(2026, 5, 29))
    ).all()
    assert {r.source for r in rows} == {"yfinance", "bloomberg"}


def test_duplicate_same_source_price_is_rejected(securities_session):
    _seed_security(securities_session)
    securities_session.add(
        Price(instrument_id=320193, ts=date(2026, 5, 29), close=192.0, source="yfinance")
    )
    securities_session.commit()
    securities_session.add(
        Price(instrument_id=320193, ts=date(2026, 5, 29), close=999.0, source="yfinance")
    )
    with pytest.raises(IntegrityError):
        securities_session.commit()
    securities_session.rollback()


def test_trading_calendar_unique_per_exchange_day(securities_session):
    securities_session.add(
        TradingDay(exchange="XNAS", session_date=date(2026, 5, 29), is_open=True)
    )
    securities_session.commit()
    [d] = securities_session.scalars(select(TradingDay)).all()
    assert d.exchange == "XNAS"
    assert d.is_open is True
