"""baseline: current portfolio schema

Revision ID: 0d7b71c1aece
Revises: 
Create Date: 2026-08-02 01:01:07.259124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7b71c1aece'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('db_connections',
    sa.Column('role', sa.Enum('PORTFOLIO', 'SECURITIES', 'MACRO', 'UNIVERSE', name='connectionrole'), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('sslmode', sa.String(), nullable=True),
    sa.Column('driver', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('management_firms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_credentials',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('investor_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['management_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('CIO', 'PM', 'ANALYST', 'ADMIN', name='personrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['management_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('mandate', sa.String(), nullable=False),
    sa.Column('firm_id', sa.String(), nullable=True),
    sa.Column('investor_entity_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['management_firms.id'], ),
    sa.ForeignKeyConstraint(['investor_entity_id'], ['investor_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'person_id', name='uq_book_manager')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='side'), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.Column('short_type', sa.Enum('SYSTEMATIC', 'DISCRETIONARY', 'NA', name='shorttype'), nullable=False),
    sa.Column('forward_beta', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('pm_id', sa.String(), nullable=True),
    sa.Column('analyst_id', sa.String(), nullable=True),
    sa.Column('cost_basis_method', sa.Enum('FIFO', 'AVCO', 'SPECIFIC', name='costbasismethod'), nullable=False),
    sa.Column('realised_pnl', sa.Float(), nullable=False),
    sa.Column('thesis', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analyst_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='tradeaction', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee_per_share', sa.Float(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('short_type', sa.Enum('SYSTEMATIC', 'DISCRETIONARY', 'NA', name='shorttype', native_enum=False), nullable=False),
    sa.Column('origin', sa.Enum('MANUAL', 'HEDGE', name='tradeorigin', native_enum=False), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_trade_date'), ['trade_date'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('fee_per_share', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lots')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_trade_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))

    op.drop_table('transactions')
    op.drop_table('positions')
    op.drop_table('book_managers')
    op.drop_table('portfolios')
    op.drop_table('people')
    op.drop_table('investor_entities')
    op.drop_table('provider_credentials')
    op.drop_table('management_firms')
    op.drop_table('db_connections')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
    # MANUALLY ADDED (autogenerate doesn't emit these): op.drop_table() does not drop the
    # Postgres native ENUM TYPE a dropped table's column used -- without this, a downgrade
    # followed by a re-upgrade fails with "type ... already exists" (verified empirically).
    # No-op on SQLite (native enums render as plain VARCHAR there). Dropped last, after
    # every table that referenced them is already gone.
    for enum_name in ("side", "shorttype", "costbasismethod", "personrole", "connectionrole"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
